// Generated by dts-bundle v0.5.0
// Dependencies for this module:
//   ../react
//   ../react-motion

declare module 'react-router-transition' {
    export { default as RouteTransition } from 'react-router-transition/RouteTransition';
    export { default as presets } from 'react-router-transition/presets';
}

declare module 'react-router-transition/RouteTransition' {
    import * as React from 'react';
    export interface RouteTransitionProps {
        className?: string;
        component?: string;
        pathname: string;
        atEnter: any;
        atActive: any;
        atLeave: any;
        mapStyles?: Function;
        runOnMount?: boolean;
        style?: Object;
    }
    class RouteTransition extends React.Component<RouteTransitionProps, void> {
        static defaultProps: {
            style: {};
            className: string;
            component: string;
            runOnMount: boolean;
            mapStyles: (val: any) => any;
        };
        getDefaultStyles: () => {
            key: string;
            data: string | number | true | React.ReactElement<any> | {} | (string | number | boolean | any[] | React.ReactElement<any>)[];
            style: any;
        }[];
        getStyles: () => {
            key: string;
            data: string | number | true | React.ReactElement<any> | {} | (string | number | boolean | any[] | React.ReactElement<any>)[];
            style: {};
        }[];
        willEnter: () => any;
        willLeave: () => {};
        renderRoute: (config: any) => React.DOMElement<{
            style: any;
            key: any;
        }, Element>;
        renderRoutes: (interpolatedStyles: any) => JSX.Element;
        render(): JSX.Element;
    }
    export default RouteTransition;
}

declare module 'react-router-transition/presets' {
    import { OpaqueConfig } from 'react-motion';
    var _default: {
        fade: {
            atEnter: {
                opacity: number;
            };
            atLeave: {
                opacity: OpaqueConfig;
            };
            atActive: {
                opacity: OpaqueConfig;
            };
        };
        pop: {
            atEnter: {
                scale: number;
                opacity: number;
            };
            atLeave: {
                scale: OpaqueConfig;
                opacity: OpaqueConfig;
            };
            atActive: {
                scale: OpaqueConfig;
                opacity: number;
            };
            mapStyles(styles: any): {
                opacity: any;
                transform: string;
            };
        };
        slideLeft: {
            atEnter: {
                opacity: number;
                offset: number;
            };
            atLeave: {
                opacity: OpaqueConfig;
                offset: OpaqueConfig;
            };
            atActive: {
                opacity: OpaqueConfig;
                offset: OpaqueConfig;
            };
            mapStyles(styles: any): {
                opacity: any;
                transform: string;
            };
        };
        slideRight: {
            atEnter: {
                opacity: number;
                offset: number;
            };
            atLeave: {
                opacity: OpaqueConfig;
                offset: OpaqueConfig;
            };
            atActive: {
                opacity: OpaqueConfig;
                offset: OpaqueConfig;
            };
            mapStyles(styles: any): {
                opacity: any;
                transform: string;
            };
        };
        slideUp: {
            atEnter: {
                opacity: number;
                offset: number;
            };
            atLeave: {
                opacity: OpaqueConfig;
                offset: OpaqueConfig;
            };
            atActive: {
                opacity: OpaqueConfig;
                offset: OpaqueConfig;
            };
            mapStyles(styles: any): {
                opacity: any;
                transform: string;
                position: string;
                top: number;
            };
        };
    };
    export default _default;
}

